name: app_report
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1 # Cambiado a una versión estable
  cloud_firestore: ^5.4.3 # Cambiado a una versión estable
  firebase_storage: ^12.3.2
  geolocator: ^13.0.1
  location: ^6.0.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.4+7 
  image_picker_web: ^4.0.0 
  cached_network_image: ^3.4.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
